# Generated by Django 3.1.5 on 2021-09-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20210905_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='Notes',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ppt',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
